// Mocks generated by Mockito 5.4.4 from annotations
// in shared_household_planner/test/features/split_bills/domain/usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_household_planner/core/error/failure.dart' as _i5;
import 'package:shared_household_planner/features/split_bills/domain/entities/bill.dart'
    as _i6;
import 'package:shared_household_planner/features/split_bills/domain/repositories/bill_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BillRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBillRepository extends _i1.Mock implements _i3.BillRepository {
  MockBillRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Bill>> create(_i6.Bill? bill) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [bill],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Bill>>.value(
            _FakeEither_0<_i5.Failure, _i6.Bill>(
          this,
          Invocation.method(
            #create,
            [bill],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Bill>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Bill>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Bill>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Bill>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Bill>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Bill>> getById(String? billId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [billId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Bill>>.value(
            _FakeEither_0<_i5.Failure, _i6.Bill>(
          this,
          Invocation.method(
            #getById,
            [billId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Bill>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Bill>> update(_i6.Bill? bill) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [bill],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Bill>>.value(
            _FakeEither_0<_i5.Failure, _i6.Bill>(
          this,
          Invocation.method(
            #update,
            [bill],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Bill>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> delete(String? billId) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [billId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #delete,
            [billId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
