// File generated by FlutterFire CLI & Antigravity.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHLC_cvAydqUS9UoImIe1jDuOu9KvL7YU',
    appId: '1:288243894517:web:bfeeb225fbbe3b1a805dbc',
    messagingSenderId: '288243894517',
    projectId: 'shared-household-planner',
    authDomain: 'shared-household-planner.firebaseapp.com',
    storageBucket: 'shared-household-planner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe0wSdj03ECA8rtgXAuqnEXU3s2pnkKUk',
    appId: '1:288243894517:android:7e6f22a9279b491b805dbc',
    messagingSenderId: '288243894517',
    projectId: 'shared-household-planner',
    storageBucket: 'shared-household-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_-SpYyaWHvkdOD9bHgDEKZ8y5MDO2P8Y',
    appId: '1:288243894517:ios:8cd8c918dffd3e6f805dbc',
    messagingSenderId: '288243894517',
    projectId: 'shared-household-planner',
    storageBucket: 'shared-household-planner.firebasestorage.app',
    iosBundleId: 'com.cordisapps.homesplit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_-SpYyaWHvkdOD9bHgDEKZ8y5MDO2P8Y',
    appId: '1:288243894517:ios:1950b6d7c6c48387805dbc',
    messagingSenderId: '288243894517',
    projectId: 'shared-household-planner',
    storageBucket: 'shared-household-planner.firebasestorage.app',
    iosBundleId: 'com.hatamht.homesplit',
  );
}
