// Mocks generated by Mockito 5.4.4 from annotations
// in shared_household_planner/test/features/split_bills/data/repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_household_planner/features/split_bills/data/datasources/local_bill_datasource.dart'
    as _i3;
import 'package:shared_household_planner/features/split_bills/data/models/bill_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBillModel_0 extends _i1.SmartFake implements _i2.BillModel {
  _FakeBillModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalBillDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalBillDataSource extends _i1.Mock
    implements _i3.LocalBillDataSource {
  MockLocalBillDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BillModel> addBill(_i2.BillModel? bill) => (super.noSuchMethod(
        Invocation.method(
          #addBill,
          [bill],
        ),
        returnValue: _i4.Future<_i2.BillModel>.value(_FakeBillModel_0(
          this,
          Invocation.method(
            #addBill,
            [bill],
          ),
        )),
      ) as _i4.Future<_i2.BillModel>);

  @override
  _i4.Future<List<_i2.BillModel>> getAllBills() => (super.noSuchMethod(
        Invocation.method(
          #getAllBills,
          [],
        ),
        returnValue: _i4.Future<List<_i2.BillModel>>.value(<_i2.BillModel>[]),
      ) as _i4.Future<List<_i2.BillModel>>);

  @override
  _i4.Future<_i2.BillModel> getBillById(String? billId) => (super.noSuchMethod(
        Invocation.method(
          #getBillById,
          [billId],
        ),
        returnValue: _i4.Future<_i2.BillModel>.value(_FakeBillModel_0(
          this,
          Invocation.method(
            #getBillById,
            [billId],
          ),
        )),
      ) as _i4.Future<_i2.BillModel>);

  @override
  _i4.Future<_i2.BillModel> updateBill(_i2.BillModel? bill) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBill,
          [bill],
        ),
        returnValue: _i4.Future<_i2.BillModel>.value(_FakeBillModel_0(
          this,
          Invocation.method(
            #updateBill,
            [bill],
          ),
        )),
      ) as _i4.Future<_i2.BillModel>);

  @override
  _i4.Future<void> deleteBill(String? billId) => (super.noSuchMethod(
        Invocation.method(
          #deleteBill,
          [billId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
